#!/usr/bin/env bash

here="$(cd $(dirname $0) && pwd)"
ncchecker_version="$(grep ^version ${here}/setup.py | awk '{print $3}' | tr -d \')"
ncchecker_home="/usr/local/apps/ncchecker/${ncchecker_version}"

echo "Creating Python virtualenv at $ncchecker_home ..."
virtualenv --quiet $ncchecker_home
export PATH="${ncchecker_home}/bin:$PATH"

echo "Installing the latest versin of \`pip\` ..."
pip install --quiet --upgrade pip

echo "Installing ncchecker to $ncchecker_home ..."
pip install --quiet --upgrade $here
